/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.jtattoo.plaf.noire.NoireLookAndFeel;
import data.DbConnector;
import data.Player;
import data.playerDAO;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UnsupportedLookAndFeelException;






public class PlayerMenu extends javax.swing.JFrame {

    DbConnector dbConnector;
    playerDAO playerDao;

    List<Player> searchList1;
    List<Player> searchList2;
    
    Boolean p1Selected;
    Boolean p2Selected;
    
    public PlayerMenu() {
        initComponents();
        jPanel4.setVisible(false);
        
         try {
            dbConnector = new DbConnector();
            playerDao = new playerDAO(dbConnector.getMyConn());
            
        } catch (IOException | SQLException ex) {
            Logger.getLogger(PlayerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp1 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SPbtn = new javax.swing.JRadioButton();
        MPbtn_off = new javax.swing.JRadioButton();
        MPbtn_on = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        p1NameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p1List = new javax.swing.JList();
        playBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        ScoreBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        p2NameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        p2List = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        hard = new javax.swing.JRadioButton();
        medium = new javax.swing.JRadioButton();
        easy = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mode"));

        btnGrp1.add(SPbtn);
        SPbtn.setSelected(true);
        SPbtn.setText("Single Player");
        SPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPbtnActionPerformed(evt);
            }
        });

        btnGrp1.add(MPbtn_off);
        MPbtn_off.setText("Multi Player-Offline");
        MPbtn_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPbtn_offActionPerformed(evt);
            }
        });

        btnGrp1.add(MPbtn_on);
        MPbtn_on.setText("Multi Player-Online");
        MPbtn_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPbtn_onActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MPbtn_on)
                    .addComponent(MPbtn_off)
                    .addComponent(SPbtn))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(SPbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MPbtn_off)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MPbtn_on)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Player 1")));

        p1NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1NameTxtActionPerformed(evt);
            }
        });
        p1NameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p1NameTxtKeyReleased(evt);
            }
        });

        jLabel1.setText("Player Name");

        p1List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p1List.setEnabled(false);
        p1List.setOpaque(false);
        jScrollPane1.setViewportView(p1List);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(p1NameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(p1NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(23, 23, 23))
        );

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        ScoreBtn.setText("Scores");
        ScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreBtnActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 2"));

        p2NameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p2NameTxtKeyReleased(evt);
            }
        });

        jLabel2.setText("Player Name");

        p2List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        p2List.setEnabled(false);
        p2List.setOpaque(false);
        jScrollPane2.setViewportView(p2List);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(p2NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(p2NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(23, 23, 23))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Difficulty"));

        buttonGroup1.add(hard);
        hard.setSelected(true);
        hard.setText("Hard");

        buttonGroup1.add(medium);
        medium.setText("Medium");

        buttonGroup1.add(easy);
        easy.setText("Easy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(easy)
                    .addComponent(medium)
                    .addComponent(hard))
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(hard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(easy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ScoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playBtn)
                    .addComponent(exitBtn)
                    .addComponent(ScoreBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPbtnActionPerformed
        jPanel4.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_SPbtnActionPerformed

    private void p1NameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p1NameTxtKeyReleased
        String name = p1NameTxt.getText();
        //System.out.println(name);
        searchList1=searchPlayer(name);
        DefaultListModel<String> dlm = new DefaultListModel<>();
        for(Player p : searchList1){
            //System.out.println(p.getName());
            dlm.addElement(p.getName());
        }
        p1List.setModel(dlm);
        
    }//GEN-LAST:event_p1NameTxtKeyReleased

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(1);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void ScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreBtnActionPerformed
        List<Player> allPlayers = new ArrayList<>();
        try {
            allPlayers=playerDao.getAllPlayers();
        } catch (SQLException ex) {
            Logger.getLogger(PlayerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
       new Scores(allPlayers).setVisible(true);
        
    }//GEN-LAST:event_ScoreBtnActionPerformed

    private void p2NameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p2NameTxtKeyReleased
        String name = p2NameTxt.getText();
        //System.out.println(name);
        searchList2=searchPlayer(name);
        DefaultListModel<String> dlm = new DefaultListModel<>();
        for(Player p : searchList2){
            System.out.println(p.getName());
            dlm.addElement(p.getName());
        }
        p2List.setModel(dlm);

    }//GEN-LAST:event_p2NameTxtKeyReleased

    private void p1NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1NameTxtActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        int gameMode;
        int difficulty;
        if(hard.isSelected()){difficulty=1;}
        else if(medium.isSelected()){difficulty=2;}
        else{difficulty=3;}
        
        
        
        if(SPbtn.isSelected()){gameMode =1;
        
            if(p1NameTxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Enter player name", "Error", JOptionPane.ERROR_MESSAGE, null);
                
            }
            else if(searchList1.size()!=1){
                
                new tttGUI(1,addPlayer(p1NameTxt.getText()),difficulty).setVisible(true);
                this.setVisible(false);
            }
            else{
                new tttGUI(1,searchList1.get(0),difficulty).setVisible(true);
                this.setVisible(false);
            }
        
        
        }
        else if(MPbtn_off.isSelected()){gameMode =2;
        
            if(p1NameTxt.getText().equals("")|p2NameTxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Enter players name", "Error", JOptionPane.ERROR_MESSAGE, null);

            }
            else if(searchList1.size()==1 && searchList2.size()==1){
                
                new tttGUI(2,searchList1.get(0),searchList2.get(0),difficulty).setVisible(true);
                this.setVisible(false);
            }
            else{
                Player player1=null;
                Player player2=null;
                
                if(searchList1.size()!=1){
                    player1=addPlayer(p1NameTxt.getText());
                }
                if(searchList1.size()!=1){
                    player2=addPlayer(p2NameTxt.getText());
                }
                new tttGUI(2,player1,player2,difficulty).setVisible(true);
                this.setVisible(false);
            }
        
        }
        else{gameMode =3;
            
            if(p1NameTxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Enter player name", "Error", JOptionPane.ERROR_MESSAGE, null);
                
            }
            else if(searchList1.size()!=1){
                
                new tttGUI(3,addPlayer(p1NameTxt.getText()),difficulty).setVisible(true);
                this.setVisible(false);
            }
            else{
                new tttGUI(3,searchList1.get(0),difficulty).setVisible(true);
                this.setVisible(false);
            }
        
        }
        
        
        
        
    }//GEN-LAST:event_playBtnActionPerformed

    private void MPbtn_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPbtn_onActionPerformed
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_MPbtn_onActionPerformed

    private void MPbtn_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPbtn_offActionPerformed
        jPanel4.setVisible(true);
        jPanel3.setVisible(false);
         
    }//GEN-LAST:event_MPbtn_offActionPerformed

    private List<Player> searchPlayer(String name)  {
        List<Player> list = new ArrayList<>();
        try {
            list=playerDao.searchPlayer(name);
        } catch (SQLException ex) {
            Logger.getLogger(PlayerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
       return list;
    }
    
    private Player addPlayer(String name) {
    
        
        
        Player player =new Player(name);
        try {
            playerDao.addPlayer(player);
        } catch (SQLException ex) {
            Logger.getLogger(PlayerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        JOptionPane.showMessageDialog(null, "New Player saved successfully");
        
        return player;
    }
    
    public static void main(String args[]) {
        try {
            /* Create and display the form */
            javax.swing.UIManager.setLookAndFeel(new NoireLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PlayerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayerMenu pMenu =new PlayerMenu();
                pMenu.setVisible(true);
            }
        });
    }
    
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MPbtn_off;
    private javax.swing.JRadioButton MPbtn_on;
    private javax.swing.JRadioButton SPbtn;
    private javax.swing.JButton ScoreBtn;
    private javax.swing.ButtonGroup btnGrp1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton easy;
    private javax.swing.JButton exitBtn;
    private javax.swing.JRadioButton hard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton medium;
    private javax.swing.JList p1List;
    private javax.swing.JTextField p1NameTxt;
    private javax.swing.JList p2List;
    private javax.swing.JTextField p2NameTxt;
    private javax.swing.JButton playBtn;
    // End of variables declaration//GEN-END:variables
}
