/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import static java.lang.Math.abs;
import java.util.Random;

import play.Controller;




/**
 *
 * @author Chamin
 */
public class tttGUI extends javax.swing.JFrame {
    
    Controller controller =null;

    int list1[] = {2,2,2,2,2,2,2,2,2};
    int list1ID =0;
    int list2[] = new int[9];
    int list2ID=0;
    
    int currentMark =0;
    
    
    public tttGUI() {
        initComponents();
        controller= new Controller();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp1 = new javax.swing.ButtonGroup();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        SPbtn = new javax.swing.JRadioButton();
        TPbtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnGrp1.add(SPbtn);
        SPbtn.setSelected(true);
        SPbtn.setText("Single Player");
        SPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPbtnActionPerformed(evt);
            }
        });

        btnGrp1.add(TPbtn);
        TPbtn.setText("Two Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPbtn)
                    .addComponent(TPbtn))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(SPbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TPbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        click(6,currentMark);
        btn6.setEnabled(false);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        click(9,currentMark);
        btn9.setEnabled(false);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        click(1,currentMark);
        btn1.setEnabled(false);
    }//GEN-LAST:event_btn1ActionPerformed

    private void SPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPbtnActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        click(2,currentMark);
        btn2.setEnabled(false);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
        click(3,currentMark);
        
        btn3.setEnabled(false);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        click(4,currentMark);
        btn4.setEnabled(false);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        click(5,currentMark);
        btn5.setEnabled(false);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        click(7,currentMark);
        btn7.setEnabled(false);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        click(8,currentMark);
        //btn8.setEnabled(false);
    }//GEN-LAST:event_btn8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tttGUI().setVisible(true);
            }
        });
    }
    
    public void click(int index,int mark){
        
        setMark(index, mark);  //setting icon of btn intially
        /*
        list1[index]=mark;
        list2[list2ID]=index;
        list2ID++;
                */
        
        int winner =controller.checkForWin(list1, abs(mark-1), mark);
        
        if (winner == 0){
            if(SPbtn.isSelected()){
                singlePlayer(mark);
            }
            else{
                currentMark = abs(mark-1);
            }
        }
        else if(winner == -1){
            System.out.println("**************  Com win **************");
        }
        else if(winner == -2){
            
            System.out.println("**************  user win **************");
        }
        
    }
    
    
    
    private void singlePlayer(int mark){
     
        int nextClick=controller.nextChoice(list1, list2, abs(mark-1), mark);
        
        if(nextClick==0){
            nextClick = 1 + (int)(Math.random() * ((9 - 1) + 1));   //Min + (int)(Math.random() * ((Max - Min) + 1))
        }
        
        if(mark == 0){
            setMark(nextClick,1);
        }
        if(mark == 1){
            setMark(nextClick,0);
            
        }
    }
    
    private void setMark(int nextClick,int nextMark) {
        
        System.out.println(nextClick+"***************************");
        list1[nextClick-1]=nextMark;
        
        
        list2[list2ID]=nextClick;
        
        list2ID++;
        
        if(nextMark==1){
            System.out.println("nextMark  1 in if  ******************");
            switch(nextClick){
                case 1:
                    btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 2:
                    btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 3:
                    btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 4:
                    btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 5:
                    btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 6:
                    btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 7:
                    btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 8:
                    btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                case 9:
                    btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/cross.png")));
                    break;
                default:
                    System.out.println("There is a error");
            }
        }
        else if(nextMark==0){
            System.out.println("nextMark  0 in if  ******************");
            switch(nextClick){
                case 1:
                    btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                case 2:
                    btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                case 3:
                    btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    System.out.println("btn3 image should edit");
                    break;
                case 4:
                    btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                case 5:
                    btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                case 6:
                    btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                case 7:
                    btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                case 8:
                    btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                case 9:
                    btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/nought.png")));
                    break;
                default:
                    System.out.println("There is a error");

            }
            
        }
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SPbtn;
    private javax.swing.JRadioButton TPbtn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.ButtonGroup btnGrp1;
    // End of variables declaration//GEN-END:variables

    
}
